### ISSUE TITLE
Fix TODO comments throughout the solution

### ISSUE THREAD

**Issue by LSViana** [LSViana/ydotnet#23]
This list is not final and will be accumulated as items are solved:

- [x] Make it easier to connect `OutputNative` size with pointer size in `MapEntryNative`
- [x] Remove mentions about `*Native` counterpart for event classes that don't need it
- [x] Fix tests for `XmlElement.Observe()` that weren't using a root-level `XmlElement` but should be
- [x] Fix tests for `XmlElement.Unobserve()` that weren't using a root-level `XmlElement` but should be
- [x] Fix tests for `XmlElement.Parent()` that weren't returning the correct value
- [x] Fix tests for `XmlElement.String()` that weren't testing for child `XmlText` nodes but should be
- [x] Remove mentions about read-only transactions on writeable functions (they will be tested later, after exception handling is added)
- [x] Remove mention to test `Transaction.Dispose()`
- [x] Remove comment from `Output.Object`
- [x] Remove comment from `Map.Length()`
- [x] Remove comment from `TextChannel`
- [x] Remove comment for `Doc.Guid` that will not be fixed because the GUID format isn't compatible with C#
- [x] Remove comment from `InputNative` because the size of the data can't be reduced or data will be lost
- [x] Fix the constructor of `Output` to support `null` pointer
  - [x] Update usages of `new Output()` to use `ReferenceAccessor.Access(Output)`
- [x] Implement test of getting null value from Map after fixing the Output constructor
- [x] Replace `NotImplemented` with `NotSupported` exception on the `EventBranch` constructor since all cases are now covered
- [x] Implement remaining tests marked as `[Ignore]` because they were waiting for implementations
- [ ] Implement `IEnumerator<T>.Reset()` on the following classes:
  - [ ] `ArrayEnumerator`
  - [ ] `MapEnumerator`
  - [ ] `XmlAttributeEnumerator`
  - [ ] `XmlTreeWalkerEnumerator`
  - [ ] Remove the documentation mention about these classes only supporting one-time enumeration
- [ ] Wrap the `XmlElement` with an `XmlFragment` before returning the value.
- [ ] Wrap the `XmlText` with an `XmlFragment` before returning the value.

**Comment by SebastianStehle** [comment]
@LSViana We have this TODO in the code:

```


    // TODO This is a temporary solution to track the amount of transactions a document has open.
    // It's fragile because a cloned instance of the same document won't be synchronized and if a `Transaction`
    // is opened in the cloned instance, it'll receive `null` from the Rust side and will cause the
    // `ThrowHelper.PendingTransaction()` to run (which is acceptable since it's a managed exception).
    internal void NotifyTransactionStarted()
    {
        openTransactions++;
    }

    internal void NotifyTransactionClosed()
    {
        openTransactions--;
    }
    ```
    
    
    Do you think we will ever have a final solution or shall we just remove this and also close this issue?

**Comment by LSViana** [comment]
@SebastianStehle I think we'll have some solutions if we ever look into that in detail but I didn't do it yet.

Given that, I'd just leave it there. It's not harmful and informs other developers who read the same code which is a positive detail.
